version: '3'
services:
  back-end:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000


  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
